on: push
name: CI
jobs:
  content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
          cache: 'npm'

      - name: Install
        run: npm install

      - name: script/cibuild-content
        run: script/cibuild-content

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
          cache: 'npm'

      - name: script/bootstrap
        run: script/bootstrap

      - name: script/cibuild-code
        run: script/cibuild-code

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: _site
          retention-days: 1

  lighthouse:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: _site

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
