on: push
name: CI
jobs:
  content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: 'npm'

      - name: Install
        run: npm install

      - name: script/cibuild-content
        run: script/cibuild-content

      - name: Vale
        uses: errata-ai/vale-action@v2
        with:
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
            https://github.com/errata-ai/alex/releases/latest/download/alex.zip
            https://github.com/benbalter/vale-styles/archive/refs/heads/master.zip
          files: __onlyModified
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Set up Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: 'npm'

      - name: script/bootstrap
        run: script/bootstrap

      - name: script/cibuild-code
        run: script/cibuild-code
