on: push
name: CI
jobs:
  content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Lint JS
        run: npm run lint-js
      - name: Lint JSON
        run: npm run lint-json
      - name: Lint MD
        run: npm run lint-md
      - name: Lint Text
        run: npm run lint-text
      - name: Vale
        uses: errata-ai/vale-action@v1
        with:
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
            https://github.com/errata-ai/alex/releases/latest/download/alex.zip
            https://github.com/benbalter/vale-styles/archive/refs/heads/master.zip
          files: __onlyModified
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install
        run: bundle install
      - name: Check Ruby
        run: bundle exec rubocop -D -S
      - name: Check site
        run: bundle exec rake test
      - name: Check DNS
        run: script/lint-dns
