on: push
name: Build related posts
jobs:
  build-related-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install
        run: bundle install

      - name: Build posts
        run: script/build-related-posts

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update related posts"
          